name = str(input(""))
id = int(input(""))
a = int(input(""))
b = int(input(""))
c = int(input(""))
print(f"Name:${name}")
print(f"Id:${id}")
print(f"Total:${a+b+c}")
print(f"Average:${int((a+b+c) / 3)}")